# Generated by Django 5.1 on 2024-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_in_english', models.CharField(max_length=100)),
                ('full_name_in_arabic', models.CharField(max_length=100)),
                ('doctor_profile_img', models.ImageField(blank=True, null=True, upload_to='doctors_profile_images')),
                ('english_bio', models.TextField()),
                ('arabic_bio', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('address_in_english', models.CharField(max_length=255)),
                ('address_in_arabic', models.CharField(max_length=255)),
                ('specialization_in_english', models.CharField(max_length=100)),
                ('specialization_in_arabic', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Male', 'Female')], max_length=6)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
