# Generated by Django 5.1 on 2024-09-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='default/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
